services:
  db:
    container_name: mysql-db
    image: mysql:8.4.0
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: KTC
      MYSQL_USER: user_test
      MYSQL_PASSWORD: pass_plain
    ports:
      - 3306:3306
