services:
  db:
    container_name: mysql-db
    image: mysql:8.4.0
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: money_tracker
      MYSQL_USER: user_test
      MYSQL_PASSWORD: pass
    ports:
        - 3307:3306

        
