services:
  db:
    container_name: postgres-db
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: mt
      POSTGRES_PASSWORD: mt
    ports:
      - 5432:5432
#    container_name: mysql-db
#    image: mysql:8.4.0
#    restart: unless-stopped
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: money_tracker
#      MYSQL_USER: user_test
#      MYSQL_PASSWORD: pass
#    ports:
#        - 3307:3306


        
