spring:
#  application:
#    name: Money-Tracker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/money_tracker
    username: mt
    password: mt
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/resources/ddl_schema.sql
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ithuongngoai@gmail.com
#    password: bpayuryecvxuqcog
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  devtools:
    add-properties: false
#  jackson:
#    default-property-inclusion: non_null


#server:
#  port: 9091
#
#jwt:
#  signerKey: h9E1HtLTjk8/wgPV0Vj5hdXvKVxZg/5cHmN0yZeEfJwXkqQuQsNV+CUPal87UmsW
#
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
